spring.application.name=check


# Data Source Properties
spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://ep-wandering-unit-a8mvj7fg-pooler.eastus2.azure.neon.tech/fleet_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Y1Ujwdr5XcMF

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##Local DB backup (for reference)
#spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_db
#spring.datasource.username=postgres
#spring.datasource.password=00Cina@07

# OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# JWT Security
jwt.secret=fleetcheck-pro-super-secret-key-2026-c-marc-compliance
jwt.expiration-ms=86400000